import { KIND_COPY, type GraphNode, type NodeKind, type RepoMap } from "@/lib/graph";

/**
 * The handover pack.
 *
 * What you give the developer you're about to hire, the co-founder joining, or
 * the person buying the thing. Written so both of them can read it: plain
 * English first, the technical name in brackets after, so a founder who can't
 * read code and an engineer who can are looking at the same document.
 *
 * Derived entirely from the map — no API key, no cost, works everywhere.
 */

export type HandoverPiece = {
  title: string;
  code: string;
  kind: NodeKind;
  summary: string;
  file: string;
  line: number;
  /** Plain-English names of what this piece reaches into. */
  usesNames: string[];
  /** Plain-English names of what depends on this piece. */
  usedByNames: string[];
};

export type HandoverGroup = {
  name: string;
  pieces: HandoverPiece[];
};

export type Handover = {
  repo: string;
  owner: string;
  branch: string;
  generatedOn: string;
  overview: string;
  stacks: string[];
  counts: { kind: NodeKind; label: string; count: number }[];
  groups: HandoverGroup[];
  filesScanned: number;
  filesTotal: number;
  hiddenCount: number;
};

const ORDER: NodeKind[] = ["screen", "door", "logic", "data"];

export function buildHandover(map: RepoMap): Handover {
  const byId = new Map(map.nodes.map((n) => [n.id, n]));

  const uses = new Map<string, string[]>();
  const usedBy = new Map<string, string[]>();
  for (const e of map.edges) {
    const from = byId.get(e.from);
    const to = byId.get(e.to);
    if (!from || !to) continue;
    uses.set(e.from, [...(uses.get(e.from) ?? []), to.title]);
    usedBy.set(e.to, [...(usedBy.get(e.to) ?? []), from.title]);
  }

  const toPiece = (n: GraphNode): HandoverPiece => ({
    title: n.title,
    code: n.code,
    kind: n.kind,
    summary: n.summary,
    file: n.file,
    line: n.line,
    usesNames: [...new Set(uses.get(n.id) ?? [])],
    usedByNames: [...new Set(usedBy.get(n.id) ?? [])],
  });

  // Group by feature, because that's how people think about their own app —
  // "the Reddit bit", not "the routing layer".
  const grouped = new Map<string, GraphNode[]>();
  for (const n of map.nodes) {
    const key = n.feature ?? "Everything else";
    grouped.set(key, [...(grouped.get(key) ?? []), n]);
  }

  const groups: HandoverGroup[] = [...grouped]
    .sort((a, b) => {
      if (a[0] === "Everything else") return 1;
      if (b[0] === "Everything else") return -1;
      return b[1].length - a[1].length || a[0].localeCompare(b[0]);
    })
    .map(([name, nodes]) => ({
      name,
      pieces: nodes
        .slice()
        .sort(
          (a, b) =>
            ORDER.indexOf(a.kind) - ORDER.indexOf(b.kind) ||
            a.title.localeCompare(b.title),
        )
        .map(toPiece),
    }));

  const counts = ORDER.map((kind) => ({
    kind,
    label: KIND_COPY[kind].plural,
    count: map.nodes.filter((n) => n.kind === kind).length,
  })).filter((c) => c.count > 0);

  const found = Object.values(map.stats.found).reduce((a, b) => a + b, 0);

  return {
    repo: map.repo,
    owner: map.owner,
    branch: map.branch,
    generatedOn: new Date().toLocaleDateString("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    overview: map.overview,
    stacks: map.stacks,
    counts,
    groups,
    filesScanned: map.stats.filesScanned,
    filesTotal: map.stats.filesTotal,
    hiddenCount: Math.max(0, found - map.nodes.length),
  };
}

/** The same document as a file you can email. */
export function toMarkdown(h: Handover): string {
  const out: string[] = [];

  out.push(`# ${h.repo} — how it works`);
  out.push("");
  out.push(
    `A plain-English guide to this app, generated by Codarc on ${h.generatedOn} from the \`${h.branch}\` branch.`,
  );
  out.push("");
  out.push("## What this app is");
  out.push("");
  out.push(h.overview);
  out.push("");

  if (h.stacks.length) {
    out.push(`**Built with:** ${h.stacks.join(", ")}`);
    out.push("");
  }

  out.push(
    `**In numbers:** ${h.counts.map((c) => `${c.count} ${c.label.toLowerCase()}`).join(" · ")}`,
  );
  out.push("");

  out.push("## How to read this");
  out.push("");
  for (const kind of ORDER) {
    out.push(`- **${KIND_COPY[kind].plural}** — ${KIND_COPY[kind].blurb}`);
  }
  out.push("");

  for (const group of h.groups) {
    out.push(`## ${group.name}`);
    out.push("");
    for (const p of group.pieces) {
      out.push(`### ${p.title}`);
      out.push("");
      out.push(p.summary);
      out.push("");
      out.push(`- **Type:** ${KIND_COPY[p.kind].label}`);
      out.push(`- **Technical name:** \`${p.code}\``);
      out.push(`- **Lives in:** \`${p.file}\` (line ${p.line})`);
      if (p.usesNames.length) {
        out.push(`- **Reaches into:** ${p.usesNames.join(", ")}`);
      }
      if (p.usedByNames.length) {
        out.push(`- **Relied on by:** ${p.usedByNames.join(", ")}`);
      }
      out.push("");
    }
  }

  out.push("---");
  out.push("");
  out.push(
    `Read ${h.filesScanned} of ${h.filesTotal} files.${
      h.hiddenCount
        ? ` ${h.hiddenCount} quieter pieces were left out to keep this readable.`
        : ""
    }`,
  );
  out.push("");
  out.push("Generated by Codarc — codarc.dev");

  return out.join("\n");
}
